const { SlashCommandBuilder } = require('@discordjs/builders');

module.exports = {
	data: new SlashCommandBuilder()
		.setName('cookie')
		.setDescription('How to bake cookies in 2HOL'),
	async execute(interaction) {
		return interaction.reply('How to make cookies in 2HOL:\n\n**STEP 1:** Make flour. This is done by using a sharp stone or any knife on some ripe wheat. Then use a straight or small curved branch on the wheat sheaf in order to get some threshed wheat. Pick that threshed wheat up in a bowl and grind it with a round stone to make flour.\n**STEP 2:** Make cream. Shuck a corn cob and wait for it to dry. Once it dries, put it in a bowl and grind it with any knife to become corn kernels. Feed this bowl of kernels to a cow and wait with a bucket. The cow will have a baby. Once the baby goes free the cow will be able to be milked. Milk the cow and let the whole milk sit for 2 minutes to separate. Once separated, skim the milk with a bowl to get a bowl of cream.\n**STEP 3:** Make raw sugar. Use a sharp stone or any knife to harvest some sugarcane. Then use an axe to chop a singular cane of sugar into chunks. Put the chunks in a bowl and grind them with a round stone. Add water to the sugarcane pulp and then boil it over hot coals. After 10 seconds you can take the cooked pulp off of the coals and cane juice into another bowl. Boil the cane juice to make a bowl of raw sugar.\n**STEP 4:** Make sugared cream. Combine the cream with the raw sugar to make sugared cream.\n**STEP 5:** Make cookie dough. Combine the flour with the sugared cream to get a bowl of cookie dough.\n**STEP 6:** Prepare the raw cookies. Put the cookie dough on a flat rock and smash it with a long shaft. Then add a gooseberry to the cookie. Use a plate on the flat rock to transfer the raw cookie onto the plate. You can repeat this process and stack up to 4 cookies on 1 plate.\n**STEP 7:** Cook the cookies. Fire up an adobe oven by lighting some kindling and waiting for it to go out. Cook the cookies on the hot oven.\n**STEP 8:** Enjoy your extra yum food with your family!');
	},
};