const { SlashCommandBuilder } = require('@discordjs/builders');

module.exports = {
	data: new SlashCommandBuilder()
		.setName('yfg')
		.setDescription('Yum Food Generator. Need an idea for the next food item to make?'),
	async execute(interaction) {
		const foods = ['Gooseberry', 'Wild Carrot', 'Cooked Rabbit', 'Bowl of Gooseberries', 'Berry Pie', 'Carrot Pie', 'Rabbit Pie', 'Berry Carrot Pie', 'Berry Rabbit Pie', 'Rabbit Carrot Pie', 'Berry Carrot Rabbit Pie', 'Carrot', 'Cooked Goose', 'Cooked Mutton', 'Cactus Fruit', 'Mutton Pie', 'Burdock Root', 'Wild Onion', 'Psilocybe Mushroom', 'Shucked Ear of Corn', 'Popcorn', 'Baked Potato', 'Bowl of Green Beans', 'Bowl of Sauerkraut', 'Bowl of Stew', 'Omelette', 'Bean Burrito', 'Bean Taco', 'Bowl of Carnitas', 'Pork Taco', 'Mug of Whole Milk', 'Buttered Bread on Clay Plate', 'Slice of Bread', 'Mug of Skim Milk', 'Mango Slices', 'Banana', 'Turkey Slice', 'Turkey Drumstick', 'Bowl of Turkey Broth', 'Spoon of Ice Cream', 'Wild Pepper', 'Cooked Shrimp', 'Cooked Seasoned Shrimp', 'Tomato', 'Hot Pepper', 'Onion', 'Tortilla Chip', 'Chip with Salsa', 'French Fry', 'French Fry with Ketchup', 'Sliced Pumpkin Pie', 'Baked Flatbread', 'Cheese Sandwich', 'Cheesy Mutton Sandwich', 'Cheese Wedge', 'Mug of Beer', 'Bee Comb', 'Bowl of Honey', 'Honeycomb', 'Apple', 'Sunny Egg', 'Apple Pie', 'Cooked Chicken', 'Cooked Skewered Char Fillet', 'Cooked Seasoned Char', 'Cooked Sausage', 'Cooked Bacon', 'Cooked Pork', 'Cooked Lobster', 'Cooked Crab', 'Cut Boiled Egg on Clay Plate', 'Steak Pie', 'Steak and Onion Pie', 'Pork Pie', 'Honey Bunny Pie', 'Pork and Apple Pie', 'Grapes', 'Wine Glass', 'Orange', 'Lemon', 'Split Coconut', 'Drilled Coconut', 'Cooked Beef', 'Cooked Skewered Cod Fillet', 'Cooked Seasoned Cod', 'Cooked Skewered Bass Fillet', 'Cooked Seasoned Bass', 'Cooked Skewered Pike Fillet', 'Cooked Seasoned Pike', 'Cooked Skewered Trout Fillet', 'Cooked Seasoned Trout', 'Skewered Cooked Sardines', 'Plate of Cooked Seasoned Sardines', 'Cookie', 'Roast Pig Dinner on Plate', 'Bowl of Chilli Con Carne', 'Stack of Pancakes with Syrup', 'Bowl of Cooked Rice', 'Onigiri', 'Bowl of Tomato Soup', 'Bowl of Mushroom Soup', 'Bowl of French Onion Soup', 'Mug of Hot Chocolate', 'Mason Jar with Pickled Beets', 'Chicken Stir Fry', 'Cooked Beef with Rub', 'Cooked Pork with Rub', 'Cooked Mutton with Rub', 'Pickle', 'Garlic Bulb', 'Wild Garlic', 'Pickling Cucumber', 'Mug of Lemonade', 'Mug of Orange Juice', 'Mug of Apple Juice', 'Bowl of Fish Stew', 'Slice of Pizza', 'Baked Squash Chunks', 'Wild Beet', 'Beet', 'Bowl of Maple Syrup'];
		return interaction.reply({
			content: foods[Math.floor(Math.random() * foods.length)],
			ephemeral: true
		});
	},
};